#!/usr/bin/env sh

#waybar -c $XDG_CONFIG_HOME/waybar/config-hyr.jsonc

CONFIG_FILES="$HOME/.config/waybar/config $HOME/.config/waybar/style.css"

trap "killall waybar" EXIT

while true; do
    waybar &
    inotifywait -e create,modify $CONFIG_FILES
    killall waybar
done
